language: go

go:
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=off go get github.com/frapposelli/wwhrd

script:
  - go test -v -race -cover ./...
  - go mod vendor && wwhrd check
