on: push
name: Docker build
jobs:
  build:
    name: Docker build
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/cli@master
      with:
        args: build .
